export const TILE_SIZE = 32
export const MAP_SIZE_X = 31 * TILE_SIZE
export const MAP_SIZE_Y = 28 * TILE_SIZE
export const FIELD_TILES_X = 26
export const FIELD_TILES_Y = 26
export const FIELD_SIZE_X = FIELD_TILES_X * TILE_SIZE
export const FIELD_SIZE_Y = FIELD_TILES_Y * TILE_SIZE
export const FIELD_START_X = TILE_SIZE
export const FIELD_START_Y = TILE_SIZE
export const FIELD_END_X = FIELD_START_X + FIELD_SIZE_X
export const FIELD_END_Y = FIELD_START_Y + FIELD_SIZE_Y
export const PLAYER_SPEED = 150
export const SLOW_BULLET_SPEED = 450
export const FAST_BULLET_SPEED = 900
export const ENEMIES_TOTAL = 20
export const SLOW_ENEMY_SPEED = 100
export const FAST_ENEMY_SPEED = 200
export const ANIMATION_SPEED = 16
